In [2]:
import numpy as np

# 가상의 이미지 데이터 생성 (4x4 픽셀, 흑백)
image = np.random.rand(4, 4)

# 1. Max Pooling
def max_pooling(image, pool_size):
    output_size = np.array(image.shape) // pool_size
    pooled_image = np.zeros(output_size)
    for i in range(output_size[0]):
        for j in range(output_size[1]):
            pooled_image[i, j] = np.max(image[i*pool_size:(i+1)*pool_size, j*pool_size:(j+1)*pool_size])
    return pooled_image
    
pooled_image = max_pooling(image, 2)

print(image)
print(pooled_image)


[[0.11851905 0.5089495  0.21906537 0.74760405]
 [0.0436764  0.83243664 0.06062719 0.47807376]
 [0.27002704 0.82064056 0.88605243 0.77522574]
 [0.94099695 0.36607503 0.16260684 0.5074163 ]]
[[0.83243664 0.74760405]
 [0.94099695 0.88605243]]


In [10]:
import numpy as np

image = np.random.rand(4,4)

# 2 & 3. Padding (Zero-padding)
def padding(image, pad_width):
     if pad_width < 1:
        return image
     else:
        height, width = image.shape
        # 새로운 이미지의 높이와 너비 계산
        new_height = height + 2*pad_width
        new_width = width + 2*pad_width
        # 0으로 채워진 새로운 이미지 생성
        padded_image = np.zeros((new_height, new_width))
        # 원본 이미지를 새 이미지의 중앙에 배치
        padded_image[pad_width:-pad_width, pad_width:-pad_width] = image
        return padded_image
         
def crop(image, start_row, start_col, height, width):
    # 주어진 시작점과 높이, 너비를 사용하여 이미지를 자름
    cropped_image = image[start_row:start_row+height, start_col:start_col+width]
    return cropped_image

# 적용 예시
padded_image = padding(image,1)
cropped_image = crop(image,1,1,2,2)
print(image)
print(padded_image)
print(cropped_image)

[[0.38707933 0.2530245  0.88388918 0.07241481]
 [0.45119093 0.66932842 0.8236319  0.08690929]
 [0.29212855 0.79569632 0.34400005 0.0020026 ]
 [0.6270108  0.20089417 0.53458034 0.2937728 ]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.38707933 0.2530245  0.88388918 0.07241481 0.        ]
 [0.         0.45119093 0.66932842 0.8236319  0.08690929 0.        ]
 [0.         0.29212855 0.79569632 0.34400005 0.0020026  0.        ]
 [0.         0.6270108  0.20089417 0.53458034 0.2937728  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
[[0.66932842 0.8236319 ]
 [0.79569632 0.34400005]]


In [12]:
import numpy as np

image = np.random.rand(4, 4)

def flip_image(image, axis):
    # Assuming image is a 2D or 3D numpy array
    if axis == 'horizontal':
        # Flip horizontally
        return image[:, ::-1]
    elif axis == 'vertical':
        # Flip vertically
        return image[::-1, :]
    else:
        raise ValueError("Axis must be 'horizontal' or 'vertical'")
flipped_image = flip_image(image, 'horizontal')
print(image)
print(flipped_image)


[[0.42657017 0.25926069 0.76859878 0.24212843]
 [0.70975931 0.53024716 0.80688732 0.92068648]
 [0.67829999 0.40697591 0.2778079  0.09027853]
 [0.07075926 0.86752488 0.24122571 0.95691614]]
[[0.24212843 0.76859878 0.25926069 0.42657017]
 [0.92068648 0.80688732 0.53024716 0.70975931]
 [0.09027853 0.2778079  0.40697591 0.67829999]
 [0.95691614 0.24122571 0.86752488 0.07075926]]


In [13]:
import numpy as np
image = np.random.rand(4, 4)
# 6. Flatten
def flatten(image):
    return image.flatten()
# 7. Normalization
def normalize(image):
    return (image - np.min(image)) / (np.max(image) - np.min(image))
# 적용 예시
flattened_image = flatten(image)
normalized_image = normalize(image)

print(image)
print(flattened_image)
print(normalized_image)

[[0.8610963  0.21414528 0.72156418 0.62788133]
 [0.91453338 0.85769296 0.70964614 0.63300469]
 [0.41869039 0.90661413 0.25833853 0.63708737]
 [0.53615208 0.5321707  0.86044261 0.08701328]]
[0.8610963  0.21414528 0.72156418 0.62788133 0.91453338 0.85769296
 0.70964614 0.63300469 0.41869039 0.90661413 0.25833853 0.63708737
 0.53615208 0.5321707  0.86044261 0.08701328]
[[0.93542504 0.15363011 0.76681026 0.6536011 ]
 [1.         0.93131234 0.75240814 0.65979232]
 [0.40080853 0.99043015 0.20703454 0.66472595]
 [0.54275274 0.53794152 0.9346351  0.        ]]
